name: CI

on: pull_request

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    steps:
      - name: Setup master branch for commitlint
        uses: actions/checkout@v2
        # https://github.com/conventional-changelog/commitlint/issues/6
      - run: git remote set-branches origin master && git fetch
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test